services:
  # Backend Flask
  - type: web
    name: chat-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "cd flask_backend && pip install -r requirements.txt"
    startCommand: "cd flask_backend && python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        value: 5000
    healthCheckPath: /
    
  # Frontend React
  - type: web
    name: chat-frontend
    env: static
    region: oregon
    plan: free
    branch: main
    buildCommand: "cd react_frontend && npm install && REACT_APP_BACKEND_URL=$BACKEND_URL npm run build"
    staticPublishPath: react_frontend/build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
